### ISSUE TITLE
placeholder rendering messed with default value placeholder value

### ISSUE THREAD

**Issue by anilios** [mrazadar/react-native-mentions-editor#2]
in readme file placeholder spellings are incorrect.. is that intensional?

See attached screen shot..
![Screenshot 2019-11-12 at 12 42 42 PM](https://user-images.githubusercontent.com/694814/68650084-24b85380-054a-11ea-9811-ac9ded9081f0.png)

**Comment by anilios** [comment]
see attached screen shot..

**Comment by anilios** [comment]
Here is the solution for the time being, I have used to fix the issue..
![Screenshot 2019-11-12 at 1 22 12 PM](https://user-images.githubusercontent.com/694814/68652473-8c24d200-054f-11ea-8e1c-29a401551c06.png)

**Comment by mrazadar** [comment]
@anilios please use latest (1.0.8) version if this works for you. 

Tested on iOS and it's working fine with the latest version.

**Comment by anilios** [comment]
ok thanks, I will check and use.

**Comment by anilios** [comment]
I am already using 1.0.11

**Comment by anilios** [comment]
can you please check android crash due to setSpan error?
[Crash on Android #12](https://github.com/mrazadar/react-native-mentions-editor/issues/12)
