### ISSUE TITLE
Dynamic UserList

### ISSUE THREAD

**Issue by Psiiirus** [mrazadar/react-native-mentions-editor#4]
Hiya,
I love this lib and i hope you will keep maintaining it :)
Did you think of offering a way to not just use a static userList and also implement a way to use a dynamic server call to fetch the users on the fly?

**Comment by mrazadar** [comment]
Hi @Psiiirus this is out of scope at the moment. 
Yes I can definitely do that but do not have enough bandwidth to make this change. 

+ Looking for maintainers 

You can still use this package and implement dynamic list by your own with the `onChangeHandler`.

**Comment by Psiiirus** [comment]
> Hi @Psiiirus this is out of scope at the moment.
> Yes I can definitely do that but do not have enough bandwidth to make this change.
> 
> * Looking for maintainers
> 
> You can still use this package and implement dynamic list by your own with the `onChangeHandler`.

Okay cool,  i will properly replace my current mentions-editor in the near future ...lets see if i will do a PR then ;)

**Comment by mrazadar** [comment]
Good luck with that.
