### ISSUE TITLE
Mention user ID is always undefined

### ISSUE THREAD

**Issue by mantissa7** [mrazadar/react-native-mentions-editor#6]
The mention user ID is always undefined resulting in `0-undefined-0`, `1-undefined-1`, etc.

I've created a pull request #5 to fix

**Comment by mrazadar** [comment]
Thanks @mantissa7 for pointing out this, and thank you for the pull request. I have resolved this issue in the actual function. Please use latest (1.0.8) version to have this fix.

**Comment by mantissa7** [comment]
Thanks!
